"""create_table

Revision ID: 151a93aedf94
Revises: 16043cb226d3
Create Date: 2022-11-16 18:50:41.066618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151a93aedf94'
down_revision = '16043cb226d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findG', sa.Column('people', sa.Integer(), nullable=True))
    op.add_column('findG', sa.Column('peopleCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findG', 'peopleCount')
    op.drop_column('findG', 'people')
    # ### end Alembic commands ###
