"""empty message

Revision ID: 16043cb226d3
Revises: d386b01f935d
Create Date: 2022-11-14 13:38:29.478623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16043cb226d3'
down_revision = 'd386b01f935d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.Unicode(length=128), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modifyTime', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Unicode(length=32), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('userId2', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('fee2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pleEat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('findG_id', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modifyTime', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['findG_id'], ['findG.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pleEat')
    op.drop_table('success')
    op.drop_table('findG')
    # ### end Alembic commands ###
