"""empty message

Revision ID: 1e6ac6f863e5
Revises: ba2259c292a2
Create Date: 2022-12-01 13:47:10.226330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6ac6f863e5'
down_revision = 'ba2259c292a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findG', 'photo')
    op.drop_constraint(None, 'success', type_='foreignkey')
    op.drop_column('success', 'userId2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('success', sa.Column('userId2', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'success', 'users', ['userId2'], ['id'])
    op.add_column('findG', sa.Column('photo', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
