"""empty message

Revision ID: 394c24785607
Revises: fda17d1c0885
Create Date: 2022-12-04 19:47:55.811706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394c24785607'
down_revision = 'fda17d1c0885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeSummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cityName', sa.Unicode(length=64), nullable=True),
    sa.Column('totalFee', sa.Integer(), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.Column('modTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeSummary')
    # ### end Alembic commands ###
