"""empty message

Revision ID: ba2259c292a2
Revises: 151a93aedf94
Create Date: 2022-11-25 17:04:08.385661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2259c292a2'
down_revision = '151a93aedf94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findG', sa.Column('photos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findG', 'photos')
    # ### end Alembic commands ###
