"""empty message

Revision ID: bda1c921ce73
Revises: 394c24785607
Create Date: 2022-12-05 20:45:07.529092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda1c921ce73'
down_revision = '394c24785607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeSummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cityName', sa.Unicode(length=64), nullable=True),
    sa.Column('totalFee', sa.Integer(), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.Column('modTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('success', sa.Column('findGId', sa.Integer(), nullable=True))
    op.add_column('success', sa.Column('cityName', sa.Unicode(length=64), nullable=True))
    op.add_column('success', sa.Column('type', sa.Unicode(length=32), nullable=True))
    op.create_foreign_key(None, 'success', 'findG', ['findGId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'success', type_='foreignkey')
    op.drop_column('success', 'type')
    op.drop_column('success', 'cityName')
    op.drop_column('success', 'findGId')
    op.drop_table('feeSummary')
    # ### end Alembic commands ###
