"""empty message

Revision ID: d386b01f935d
Revises: 
Create Date: 2022-11-09 22:35:01.715933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd386b01f935d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_timestamp', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_comments_timestamp', table_name='comments')
    op.drop_table('comments')
    op.add_column('users', sa.Column('realName', sa.Unicode(length=64), nullable=True))
    op.add_column('users', sa.Column('documentTypeName', sa.Unicode(length=64), nullable=True))
    op.add_column('users', sa.Column('documentNumber', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('phoneNumber', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('introduce', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('cityName', sa.Unicode(length=64), nullable=True))
    op.add_column('users', sa.Column('createTime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('modifyTime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role_str', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_str')
    op.drop_column('users', 'modifyTime')
    op.drop_column('users', 'createTime')
    op.drop_column('users', 'cityName')
    op.drop_column('users', 'introduce')
    op.drop_column('users', 'level')
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'documentNumber')
    op.drop_column('users', 'documentTypeName')
    op.drop_column('users', 'realName')
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_timestamp', 'comments', ['timestamp'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('body_html', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_timestamp', 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###
