"""empty message

Revision ID: fda17d1c0885
Revises: 1e6ac6f863e5
Create Date: 2022-12-04 19:22:07.284524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda17d1c0885'
down_revision = '1e6ac6f863e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('type', sa.Unicode(length=32), nullable=True),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('people', sa.Integer(), nullable=True),
    sa.Column('peopleCount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('endTime', sa.DateTime(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modifyTime', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Unicode(length=32), nullable=True),
    sa.Column('photos', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('fee2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pleEat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('findG_id', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('modifyTime', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['findG_id'], ['findG.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('success_commenter',
    sa.Column('success_id', sa.Integer(), nullable=True),
    sa.Column('commentor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['success_id'], ['success.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('success_commenter')
    op.drop_table('pleEat')
    op.drop_table('success')
    op.drop_table('findG')
    # ### end Alembic commands ###
